### ISSUE TITLE
RuntimeError: downsample feature map of size torch.Size([1, 64, 135, 240])

### ISSUE THREAD

**Issue by wolf943134497** [cvlab-epfl/disk#5]
Hi @ducha-aiki @jatentaki  Thanks for your great works! I met some errors:
Traceback (most recent call last):
  File "detect.py", line 249, in <module>
    described_samples = extract(dataset, args.h5_path)
  File "detect.py", line 201, in extract
    batched_features = extract(bitmaps)
  File "/home/anaconda3/envs/pytorch1/lib/python3.6/site-packages/torch_dimcheck/dimcheck.py", line 110, in wrapped
    result = func(*args, **kwargs)
  File "/home/disk/disk/model/disk.py", line 57, in features
    descriptors, heatmaps = self._split(self.unet(images))
  File "/home/anaconda3/envs/pytorch1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/pytorch1/lib/python3.6/site-packages/torch_dimcheck/dimcheck.py", line 110, in wrapped
    result = func(*args, **kwargs)
  File "/home/anaconda3/envs/pytorch1/lib/python3.6/site-packages/unets/unet.py", line 100, in forward
    features.append(layer(features[-1]))
  File "/home/anaconda3/envs/pytorch1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/pytorch1/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/anaconda3/envs/pytorch1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/pytorch1/lib/python3.6/site-packages/unets/ops.py", line 42, in forward
    raise RuntimeError(msg)
RuntimeError: Trying to downsample feature map of size torch.Size([1, 64, 135, 240])

which version of pytorch? any suggestions?  Thanks!

**Comment by ducha-aiki** [comment]
I am not the author, please don't assign to me a credit for creating DISK.

Regarding your question --- set resize values to be power of 2, e.g. 1024x768.
Altough I would also prefer to hear about more robust solution from @jatentaki

**Comment by jatentaki** [comment]
Haha, @ducha-aiki is not a maintainer but apparently responds even faster than I do.

More precisely, it has to be not only power of 2, but multiples of 16 (since we have 4 downsampling steps, each reducing the resolution by 2 --> 2^4 = 16). In practice, please set the `--height` and `--width` flags to a size which is closest to your input size and divisible by 16 (don't worry if it doesn't exactly preserve the aspect ratio, it will internally maintain it with padding).

**Comment by jatentaki** [comment]
I added more informative exception messages around this issue. @wolf943134497 is the problem resolved?

**Comment by wolf943134497** [comment]
@jatentaki  the problem is solved! Thanks for your suggestions and great works!
Sorry to disturb you, ducha-aiki. Thanks for your help!

**Comment by KillerQueen1024** [comment]
@wolf943134497 你好， 我是LIO-wheel-fusion 项目 这个原始仓库的主人，吴新锐。 lio-wheel-fusion工程， 是我们内部项目，因为设计项目保密协议
之前误上传至了github，现原始仓库 lio-wheel-fusion 已经删除， 请您看到此消息后， 删除此 fork 得到的仓库， 谢谢合作！！！！
或者看到此条消息后，尽快联系邮箱  916806487 或者电话 15201978695！！  谢谢合作！！

如有疑问请联系  916806487@sjtu.edu.cn   或者电话致电  15201978695 ，谢谢合作！
